/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.uniqueplayers.speditionsverwaltung.gui;

/**
 *
 * @author Oberleutnant20
 */
public class Main extends javax.swing.JFrame {
    
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fra_reg = new javax.swing.JFrame();
        register_lab_Header = new javax.swing.JLabel();
        register_lab_EMail = new javax.swing.JLabel();
        register_lab_userName = new javax.swing.JLabel();
        register_lab_passwd = new javax.swing.JLabel();
        register_lab_passwd_repeat = new javax.swing.JLabel();
        register_tf_username = new javax.swing.JTextField();
        register_tf_mail = new javax.swing.JTextField();
        register_pf_passwd = new javax.swing.JPasswordField();
        register_pf_passwd_repeat = new javax.swing.JPasswordField();
        register_bu_registrieren = new javax.swing.JButton();
        register_bu_back = new javax.swing.JButton();
        register_lab_copyright = new javax.swing.JLabel();
        dia_reg = new javax.swing.JDialog();
        dia_reg_ta_thx = new javax.swing.JTextArea();
        dia_reg_bu_main = new javax.swing.JButton();
        dia_reg_lab_copyright = new javax.swing.JLabel();
        fra_login = new javax.swing.JFrame();
        login_lab_Header = new javax.swing.JLabel();
        login_tf_userName = new javax.swing.JTextField();
        login_lab_userName = new javax.swing.JLabel();
        login_lab_passwd = new javax.swing.JLabel();
        login_pf_passwd = new javax.swing.JPasswordField();
        login_lab_copyright = new javax.swing.JLabel();
        login_bu_loginFin = new javax.swing.JButton();
        main_lab_header = new javax.swing.JLabel();
        main_lab_copyright = new javax.swing.JLabel();
        main_bu_reg = new javax.swing.JButton();
        main_bu_login = new javax.swing.JButton();

        fra_reg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        fra_reg.setMinimumSize(new java.awt.Dimension(376, 273));
        fra_reg.setName("Registrieren"); // NOI18N
        fra_reg.setResizable(false);

        register_lab_Header.setText("<html><h5>Registrieren</h5></html>");

        register_lab_EMail.setText("<html><strong>E-Mail</strong></html>");

        register_lab_userName.setText("<html><strong>Benutzername</strong></html>");

        register_lab_passwd.setText("<html><strong>Passwort</strong></htm>");

        register_lab_passwd_repeat.setText("<html><strong>Passwort wiederholen</strong></html>");

        register_pf_passwd.setText("jPasswordField1");

        register_pf_passwd_repeat.setText("jPasswordField2");

        register_bu_registrieren.setText("Registrieren");
        register_bu_registrieren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_bu_registrierenActionPerformed(evt);
            }
        });

        register_bu_back.setText("Abbrechen");
        register_bu_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_bu_backActionPerformed(evt);
            }
        });

        register_lab_copyright.setText("©unique-players.de");

        javax.swing.GroupLayout fra_regLayout = new javax.swing.GroupLayout(fra_reg.getContentPane());
        fra_reg.getContentPane().setLayout(fra_regLayout);
        fra_regLayout.setHorizontalGroup(
            fra_regLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fra_regLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fra_regLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fra_regLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(fra_regLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fra_regLayout.createSequentialGroup()
                                .addComponent(register_lab_copyright)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fra_regLayout.createSequentialGroup()
                                .addGroup(fra_regLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(register_bu_back)
                                    .addComponent(register_lab_Header, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(144, 144, 144))))
                    .addGroup(fra_regLayout.createSequentialGroup()
                        .addGroup(fra_regLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fra_regLayout.createSequentialGroup()
                                .addGroup(fra_regLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(register_lab_passwd_repeat)
                                    .addComponent(register_lab_EMail)
                                    .addComponent(register_lab_userName)
                                    .addComponent(register_lab_passwd))
                                .addGroup(fra_regLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(fra_regLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(fra_regLayout.createSequentialGroup()
                                            .addGap(90, 90, 90)
                                            .addComponent(register_tf_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(register_tf_username, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fra_regLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(fra_regLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(register_pf_passwd, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                            .addComponent(register_pf_passwd_repeat)))))
                            .addGroup(fra_regLayout.createSequentialGroup()
                                .addComponent(register_bu_registrieren)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        fra_regLayout.setVerticalGroup(
            fra_regLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fra_regLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(register_lab_Header, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fra_regLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(register_lab_EMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(register_tf_mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fra_regLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(register_lab_userName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(register_tf_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fra_regLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(register_lab_passwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(register_pf_passwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fra_regLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(register_lab_passwd_repeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(register_pf_passwd_repeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(fra_regLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(register_bu_registrieren)
                    .addComponent(register_bu_back))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(register_lab_copyright)
                .addContainerGap())
        );

        register_lab_Header.getAccessibleContext().setAccessibleName("<html><h3>Registrieren</h3></html>");

        dia_reg.setMinimumSize(new java.awt.Dimension(498, 151));

        dia_reg_ta_thx.setEditable(false);
        dia_reg_ta_thx.setColumns(20);
        dia_reg_ta_thx.setRows(5);
        dia_reg_ta_thx.setText("Vielen Dank, dass Sie sich registriert haben.\n\nBei Fragen und Anregungen steht Ihnen das Support-/Adminteam \nvon Unique-Players.de gerne zur verfügung oder schreiben Sie uns eine \nMail an: support@unique-players.de");

        dia_reg_bu_main.setText("Startseite");
        dia_reg_bu_main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dia_reg_bu_mainActionPerformed(evt);
            }
        });

        dia_reg_lab_copyright.setText("©unique-players.de");

        javax.swing.GroupLayout dia_regLayout = new javax.swing.GroupLayout(dia_reg.getContentPane());
        dia_reg.getContentPane().setLayout(dia_regLayout);
        dia_regLayout.setHorizontalGroup(
            dia_regLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dia_regLayout.createSequentialGroup()
                .addGroup(dia_regLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dia_regLayout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(dia_reg_bu_main)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dia_reg_lab_copyright))
                    .addGroup(dia_regLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(dia_reg_ta_thx, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)))
                .addContainerGap())
        );
        dia_regLayout.setVerticalGroup(
            dia_regLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dia_regLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dia_reg_ta_thx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dia_regLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dia_reg_bu_main)
                    .addComponent(dia_reg_lab_copyright))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        fra_login.setMinimumSize(new java.awt.Dimension(363, 181));
        fra_login.setName("login"); // NOI18N
        fra_login.setResizable(false);

        login_lab_Header.setText("<html><center><h2>Login</h2></center></html>");

        login_lab_userName.setText("<html><strong>Benutzername</strong></html>");

        login_lab_passwd.setText("<html><strong>Passwort</strong></html>");

        login_pf_passwd.setText("jPasswordField1");

        login_lab_copyright.setText("©unique-players.de");

        login_bu_loginFin.setText("Login");
        login_bu_loginFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_bu_loginFinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fra_loginLayout = new javax.swing.GroupLayout(fra_login.getContentPane());
        fra_login.getContentPane().setLayout(fra_loginLayout);
        fra_loginLayout.setHorizontalGroup(
            fra_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fra_loginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fra_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fra_loginLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(fra_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fra_loginLayout.createSequentialGroup()
                                .addComponent(login_lab_Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(142, 142, 142))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fra_loginLayout.createSequentialGroup()
                                .addComponent(login_lab_copyright)
                                .addContainerGap())))
                    .addGroup(fra_loginLayout.createSequentialGroup()
                        .addGroup(fra_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(login_bu_loginFin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(login_lab_passwd)
                            .addComponent(login_lab_userName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                        .addGroup(fra_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(login_pf_passwd)
                            .addComponent(login_tf_userName))
                        .addContainerGap())))
        );
        fra_loginLayout.setVerticalGroup(
            fra_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fra_loginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(login_lab_Header, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(fra_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login_tf_userName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login_lab_userName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fra_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(login_lab_passwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login_pf_passwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(fra_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login_lab_copyright)
                    .addComponent(login_bu_loginFin))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Speditionsverwaltung für ETS2/ATS");
        setName("main"); // NOI18N
        setResizable(false);

        main_lab_header.setText("<html><h1>Speditionsverwaltung</h1></html>");

        main_lab_copyright.setText("©unique-players.de");

        main_bu_reg.setText("Registrieren");
        main_bu_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                main_bu_regActionPerformed(evt);
            }
        });

        main_bu_login.setText("Anmelden");
        main_bu_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                main_bu_loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(main_lab_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(main_bu_reg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(main_bu_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(213, 213, 213))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(main_lab_copyright)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(main_lab_header, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(main_bu_reg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(main_bu_login)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(main_lab_copyright)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void main_bu_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_main_bu_regActionPerformed
        reg();
    }//GEN-LAST:event_main_bu_regActionPerformed

    private void main_bu_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_main_bu_loginActionPerformed
        goToLogin();
    }//GEN-LAST:event_main_bu_loginActionPerformed

    private void register_bu_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_bu_backActionPerformed
        backToMain_reg();
    }//GEN-LAST:event_register_bu_backActionPerformed

    private void register_bu_registrierenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_bu_registrierenActionPerformed
        reg_finish();
    }//GEN-LAST:event_register_bu_registrierenActionPerformed

    private void dia_reg_bu_mainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dia_reg_bu_mainActionPerformed
        backToMain();
    }//GEN-LAST:event_dia_reg_bu_mainActionPerformed

    private void login_bu_loginFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_bu_loginFinActionPerformed
        login();
    }//GEN-LAST:event_login_bu_loginFinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //Logfile??
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog dia_reg;
    private javax.swing.JButton dia_reg_bu_main;
    private javax.swing.JLabel dia_reg_lab_copyright;
    private javax.swing.JTextArea dia_reg_ta_thx;
    private javax.swing.JFrame fra_login;
    private javax.swing.JFrame fra_reg;
    private javax.swing.JButton login_bu_loginFin;
    private javax.swing.JLabel login_lab_Header;
    private javax.swing.JLabel login_lab_copyright;
    private javax.swing.JLabel login_lab_passwd;
    private javax.swing.JLabel login_lab_userName;
    private javax.swing.JPasswordField login_pf_passwd;
    private javax.swing.JTextField login_tf_userName;
    private javax.swing.JButton main_bu_login;
    private javax.swing.JButton main_bu_reg;
    private javax.swing.JLabel main_lab_copyright;
    private javax.swing.JLabel main_lab_header;
    private javax.swing.JButton register_bu_back;
    private javax.swing.JButton register_bu_registrieren;
    private javax.swing.JLabel register_lab_EMail;
    private javax.swing.JLabel register_lab_Header;
    private javax.swing.JLabel register_lab_copyright;
    private javax.swing.JLabel register_lab_passwd;
    private javax.swing.JLabel register_lab_passwd_repeat;
    private javax.swing.JLabel register_lab_userName;
    private javax.swing.JPasswordField register_pf_passwd;
    private javax.swing.JPasswordField register_pf_passwd_repeat;
    private javax.swing.JTextField register_tf_mail;
    private javax.swing.JTextField register_tf_username;
    // End of variables declaration//GEN-END:variables

    // Platz für eigene Variablen
    
    
    
    
    
    
    
    // Methoden die in den Frames genutzt werden
    private void reg() {
        fra_reg.setVisible(true);
    }

    private void goToLogin() {
        fra_login.setVisible(true);
    }

    private void reg_finish() {
        fra_reg.setVisible(false);
        dia_reg.setVisible(true);
    }

    private void backToMain() {
        dia_reg.setVisible(false);
    }

    private void backToMain_reg() {
        fra_reg.setVisible(false);
    }

    private void login() {
        
    }
}
